# Generated by Django 6.0.7 on 2026-07-28 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_patient_discharge_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='Hospital.patient')),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
    ]
