# Generated by Django 5.0.14 on 2026-07-30 06:55

import Hospital.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0009_update_role_permissions_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/', validators=[Hospital.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_tests/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx']), Hospital.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx']), Hospital.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/', validators=[Hospital.models.validate_file_size]),
        ),
    ]
